# Generated by Django 3.2 on 2022-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='baho',
            field=models.IntegerField(verbose_name='Baho'),
        ),
    ]
