# Generated by Django 3.2 on 2022-07-25 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20220718_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Mahsulot turi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Mahsulot turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='baho',
            field=models.IntegerField(verbose_name='Baho'),
        ),
    ]
