# Generated by Django 3.2 on 2022-07-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220730_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, unique=True), max_length=255),
        ),
    ]
