# Generated by Django 3.2 on 2022-07-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220730_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255), max_length=255, verbose_name=''),
        ),
    ]
