# Generated by Django 3.2 on 2022-07-30 05:10

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255, verbose_name='Price')),
                ('content', models.TextField(verbose_name='Content')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('cash', models.BooleanField(verbose_name='Cash')),
                ('card', models.BooleanField(verbose_name='Card')),
                ('active', models.BooleanField(verbose_name='Active')),
                ('slug', models.SlugField(default=models.CharField(max_length=255), max_length=255, verbose_name='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Group',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='result',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.group'),
        ),
    ]
