# Generated by Django 3.2 on 2022-07-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='category',
        ),
        migrations.AddField(
            model_name='result',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.group'),
        ),
    ]
