# Generated by Django 3.2 on 2022-07-18 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('slug', models.SlugField(max_length=268, unique=True, verbose_name='Slag')),
                ('discription', models.TextField(blank=True, verbose_name='Qisqacha tavsif')),
                ('content', models.TextField(verbose_name='Kontent')),
                ('image', models.ImageField(upload_to='yangilikar/', verbose_name='Rasm')),
                ('published', models.DateField(default=django.utils.timezone.now, verbose_name='Chop etilgan sana')),
            ],
            options={
                'verbose_name': 'yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
