# Generated by Django 3.2 on 2022-07-27 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqti')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'kurs',
                'verbose_name_plural': 'Dollar kursi',
            },
        ),
    ]
