# Generated by Django 3.2 on 2022-07-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220721_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Address',
            field=models.CharField(max_length=120),
        ),
    ]
