# Generated by Django 3.2 on 2022-07-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20220721_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
