# Generated by Django 3.2 on 2022-07-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contactview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactView',
            new_name='Message',
        ),
    ]
