# Generated by Django 3.2 on 2022-07-31 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0004_auto_20220627_1449'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carusel',
        ),
        migrations.AlterModelOptions(
            name='imgcategory',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Rasm kategoriyalari'},
        ),
    ]
